2019-12-27 08:53:32,970:WARNING:start thread:mq-thread
2019-12-27 08:53:32,979:WARNING:start thread:pc_lpc
2019-12-27 08:53:33,094:WARNING:custmer wait for mes---->>opc
2019-12-27 08:53:33,095:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 08:53:34,480:WARNING:insert opc  data2019-12-27 08:53:34
2019-12-27 09:11:51,769:WARNING:insert opc  data2019-12-27 09:11:51
2019-12-27 09:41:57,119:WARNING:insert opc  data2019-12-27 09:41:57
2019-12-27 10:11:39,173:WARNING:start thread:mq-thread
2019-12-27 10:11:39,175:WARNING:start thread:pc_lpc
2019-12-27 10:11:39,224:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:11:39,228:WARNING:custmer wait for mes---->>opc
2019-12-27 10:11:49,100:WARNING:start thread:mq-thread
2019-12-27 10:11:49,107:WARNING:start thread:pc_lpc
2019-12-27 10:11:49,227:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:11:49,242:WARNING:custmer wait for mes---->>opc
2019-12-27 10:12:01,844:WARNING:insert opc  data2019-12-27 10:12:01
2019-12-27 10:29:23,527:WARNING:start thread:mq-thread
2019-12-27 10:29:23,549:WARNING:start thread:pc_lpc
2019-12-27 10:29:23,630:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:29:23,673:WARNING:custmer wait for mes---->>opc
2019-12-27 10:35:11,642:WARNING:start thread:mq-thread
2019-12-27 10:35:11,652:WARNING:start thread:pc_lpc
2019-12-27 10:35:11,757:WARNING:custmer wait for mes---->>opc
2019-12-27 10:35:11,765:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:37:51,096:WARNING:start thread:mq-thread
2019-12-27 10:37:51,101:WARNING:start thread:pc_lpc
2019-12-27 10:37:51,213:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:37:51,234:WARNING:custmer wait for mes---->>opc
2019-12-27 10:38:32,462:WARNING:start thread:mq-thread
2019-12-27 10:38:32,470:WARNING:start thread:pc_lpc
2019-12-27 10:38:32,592:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:38:32,617:WARNING:custmer wait for mes---->>opc
2019-12-27 10:38:58,047:WARNING:start thread:mq-thread
2019-12-27 10:38:58,053:WARNING:start thread:pc_lpc
2019-12-27 10:38:58,197:WARNING:custmer wait for mes---->>opc
2019-12-27 10:38:58,215:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:39:07,264:WARNING:start thread:mq-thread
2019-12-27 10:39:07,269:WARNING:start thread:pc_lpc
2019-12-27 10:39:07,396:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:39:07,423:WARNING:custmer wait for mes---->>opc
2019-12-27 10:39:44,045:WARNING:start thread:mq-thread
2019-12-27 10:39:44,050:WARNING:start thread:pc_lpc
2019-12-27 10:39:44,154:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:39:44,200:WARNING:custmer wait for mes---->>opc
2019-12-27 10:40:33,887:WARNING:start thread:pc_lpc
2019-12-27 10:40:33,866:WARNING:start thread:mq-thread
2019-12-27 10:40:33,987:WARNING:custmer wait for mes---->>opc
2019-12-27 10:40:34,002:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:41:36,766:WARNING:start thread:pc_lpc
2019-12-27 10:41:36,760:WARNING:start thread:mq-thread
2019-12-27 10:41:36,861:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:41:36,919:WARNING:custmer wait for mes---->>opc
2019-12-27 10:41:42,911:WARNING:start thread:mq-thread
2019-12-27 10:41:42,917:WARNING:start thread:pc_lpc
2019-12-27 10:41:43,028:WARNING:custmer wait for mes---->>opc
2019-12-27 10:41:43,089:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:42:06,853:WARNING:insert opc  data2019-12-27 10:42:06
2019-12-27 10:43:23,853:WARNING:start thread:mq-thread
2019-12-27 10:43:23,859:WARNING:start thread:pc_lpc
2019-12-27 10:43:23,990:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:43:24,000:WARNING:custmer wait for mes---->>opc
2019-12-27 10:46:16,601:WARNING:start thread:mq-thread
2019-12-27 10:46:16,609:WARNING:start thread:pc_lpc
2019-12-27 10:46:16,764:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:46:16,768:WARNING:custmer wait for mes---->>opc
2019-12-27 10:48:14,924:WARNING:start thread:mq-thread
2019-12-27 10:48:14,930:WARNING:start thread:pc_lpc
2019-12-27 10:48:15,041:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 10:48:15,060:WARNING:custmer wait for mes---->>opc
2019-12-27 11:05:23,941:WARNING:start thread:mq-thread
2019-12-27 11:05:23,948:WARNING:start thread:pc_lpc
2019-12-27 11:05:24,065:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 11:05:24,082:WARNING:custmer wait for mes---->>opc
2019-12-27 11:06:20,689:WARNING:start thread:mq-thread
2019-12-27 11:06:20,726:WARNING:start thread:pc_lpc
2019-12-27 11:06:20,801:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 11:06:20,835:WARNING:custmer wait for mes---->>opc
2019-12-27 11:10:37,772:WARNING:start thread:pc_lpc
2019-12-27 11:10:37,750:WARNING:start thread:mq-thread
2019-12-27 11:10:37,883:WARNING:custmer wait for mes---->>opc
2019-12-27 11:10:37,895:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 11:12:13,413:WARNING:insert opc  data2019-12-27 11:12:13
2019-12-27 11:42:17,097:WARNING:insert opc  data2019-12-27 11:42:17
2019-12-27 12:12:21,932:WARNING:insert opc  data2019-12-27 12:12:21
2019-12-27 12:42:26,922:WARNING:insert opc  data2019-12-27 12:42:26
2019-12-27 13:12:32,311:WARNING:insert opc  data2019-12-27 13:12:32
2019-12-27 13:42:37,166:WARNING:insert opc  data2019-12-27 13:42:37
2019-12-27 14:12:42,183:WARNING:insert opc  data2019-12-27 14:12:42
2019-12-27 14:42:47,314:WARNING:insert opc  data2019-12-27 14:42:47
2019-12-27 15:04:54,741:WARNING:1264 (22003): Out of range value for column 'value' at row 1
2019-12-27 15:12:52,283:WARNING:insert opc  data2019-12-27 15:12:52
2019-12-27 15:42:57,238:WARNING:insert opc  data2019-12-27 15:42:57
2019-12-27 16:13:02,183:WARNING:insert opc  data2019-12-27 16:13:02
2019-12-27 16:33:13,960:WARNING:start thread:mq-thread
2019-12-27 16:33:13,967:WARNING:start thread:pc_lpc
2019-12-27 16:33:14,018:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2019-12-27 16:33:14,025:WARNING:custmer wait for mes---->>opc
2019-12-27 16:43:06,707:WARNING:insert opc  data2019-12-27 16:43:06
2019-12-27 17:13:11,646:WARNING:insert opc  data2019-12-27 17:13:11
2019-12-27 17:43:16,760:WARNING:insert opc  data2019-12-27 17:43:16
2019-12-27 18:13:21,526:WARNING:insert opc  data2019-12-27 18:13:21
2019-12-27 18:43:26,436:WARNING:insert opc  data2019-12-27 18:43:26
2019-12-27 19:13:31,538:WARNING:insert opc  data2019-12-27 19:13:31
2019-12-27 19:43:36,330:WARNING:insert opc  data2019-12-27 19:43:36
2019-12-27 20:13:41,310:WARNING:insert opc  data2019-12-27 20:13:41
2019-12-27 20:43:46,289:WARNING:insert opc  data2019-12-27 20:43:46
2019-12-27 21:13:51,368:WARNING:insert opc  data2019-12-27 21:13:51
2019-12-27 21:43:56,602:WARNING:insert opc  data2019-12-27 21:43:56
2019-12-27 22:14:01,391:WARNING:insert opc  data2019-12-27 22:14:01
2019-12-27 22:44:06,187:WARNING:insert opc  data2019-12-27 22:44:06
2019-12-27 23:14:11,142:WARNING:insert opc  data2019-12-27 23:14:11
2019-12-27 23:44:16,179:WARNING:insert opc  data2019-12-27 23:44:16
2019-12-28 00:14:20,938:WARNING:insert opc  data2019-12-28 00:14:20
2019-12-28 00:44:26,184:WARNING:insert opc  data2019-12-28 00:44:26
2019-12-28 01:14:31,127:WARNING:insert opc  data2019-12-28 01:14:31
2019-12-28 01:44:35,934:WARNING:insert opc  data2019-12-28 01:44:35
2019-12-28 02:14:40,506:WARNING:insert opc  data2019-12-28 02:14:40
2019-12-28 02:44:45,288:WARNING:insert opc  data2019-12-28 02:44:45
2019-12-28 03:14:50,297:WARNING:insert opc  data2019-12-28 03:14:50
2019-12-28 03:44:55,229:WARNING:insert opc  data2019-12-28 03:44:55
2019-12-28 04:15:00,346:WARNING:insert opc  data2019-12-28 04:15:00
2019-12-28 04:45:05,233:WARNING:insert opc  data2019-12-28 04:45:05
2019-12-28 05:15:10,016:WARNING:insert opc  data2019-12-28 05:15:10
2019-12-28 05:45:14,984:WARNING:insert opc  data2019-12-28 05:45:14
2019-12-28 06:15:20,123:WARNING:insert opc  data2019-12-28 06:15:20
2019-12-28 06:45:25,043:WARNING:insert opc  data2019-12-28 06:45:25
2019-12-28 07:15:29,858:WARNING:insert opc  data2019-12-28 07:15:29
2019-12-28 07:45:34,550:WARNING:insert opc  data2019-12-28 07:45:34
2019-12-28 08:15:39,731:WARNING:insert opc  data2019-12-28 08:15:39
2019-12-28 08:45:44,728:WARNING:insert opc  data2019-12-28 08:45:44
2019-12-28 09:15:49,660:WARNING:insert opc  data2019-12-28 09:15:49
2019-12-28 09:45:54,615:WARNING:insert opc  data2019-12-28 09:45:54
2019-12-28 10:15:59,485:WARNING:insert opc  data2019-12-28 10:15:59
2019-12-28 10:46:04,414:WARNING:insert opc  data2019-12-28 10:46:04
2019-12-28 11:16:09,290:WARNING:insert opc  data2019-12-28 11:16:09
2019-12-28 11:46:14,223:WARNING:insert opc  data2019-12-28 11:46:14
2019-12-28 12:16:19,762:WARNING:insert opc  data2019-12-28 12:16:19
2019-12-28 12:46:24,313:WARNING:insert opc  data2019-12-28 12:46:24
2019-12-28 13:16:29,162:WARNING:insert opc  data2019-12-28 13:16:29
2019-12-28 13:46:33,922:WARNING:insert opc  data2019-12-28 13:46:33
2019-12-28 14:16:38,742:WARNING:insert opc  data2019-12-28 14:16:38
2019-12-28 14:46:43,663:WARNING:insert opc  data2019-12-28 14:46:43
2019-12-28 15:16:48,872:WARNING:insert opc  data2019-12-28 15:16:48
2019-12-28 15:46:53,909:WARNING:insert opc  data2019-12-28 15:46:53
2019-12-28 16:16:58,662:WARNING:insert opc  data2019-12-28 16:16:58
2019-12-28 16:47:03,388:WARNING:insert opc  data2019-12-28 16:47:03
2019-12-28 17:17:08,434:WARNING:insert opc  data2019-12-28 17:17:08
2019-12-28 17:47:13,477:WARNING:insert opc  data2019-12-28 17:47:13
2019-12-28 18:17:18,296:WARNING:insert opc  data2019-12-28 18:17:18
2019-12-28 18:47:23,077:WARNING:insert opc  data2019-12-28 18:47:23
2019-12-28 19:17:27,939:WARNING:insert opc  data2019-12-28 19:17:27
2019-12-28 19:47:32,903:WARNING:insert opc  data2019-12-28 19:47:32
2019-12-28 20:17:37,840:WARNING:insert opc  data2019-12-28 20:17:37
2019-12-28 20:47:42,737:WARNING:insert opc  data2019-12-28 20:47:42
2019-12-28 21:17:47,677:WARNING:insert opc  data2019-12-28 21:17:47
2019-12-28 21:47:52,691:WARNING:insert opc  data2019-12-28 21:47:52
2019-12-28 22:17:57,658:WARNING:insert opc  data2019-12-28 22:17:57
2019-12-28 22:48:02,417:WARNING:insert opc  data2019-12-28 22:48:02
2019-12-28 23:18:07,252:WARNING:insert opc  data2019-12-28 23:18:07
2019-12-28 23:48:12,375:WARNING:insert opc  data2019-12-28 23:48:12
2019-12-29 00:18:17,449:WARNING:insert opc  data2019-12-29 00:18:17
2019-12-29 00:48:22,552:WARNING:insert opc  data2019-12-29 00:48:22
2019-12-29 01:18:27,421:WARNING:insert opc  data2019-12-29 01:18:27
2019-12-29 01:48:32,608:WARNING:insert opc  data2019-12-29 01:48:32
2019-12-29 02:18:37,452:WARNING:insert opc  data2019-12-29 02:18:37
2019-12-29 02:48:42,407:WARNING:insert opc  data2019-12-29 02:48:42
2019-12-29 03:18:47,324:WARNING:insert opc  data2019-12-29 03:18:47
2019-12-29 03:48:52,305:WARNING:insert opc  data2019-12-29 03:48:52
2019-12-29 04:18:57,124:WARNING:insert opc  data2019-12-29 04:18:57
2019-12-29 04:49:02,106:WARNING:insert opc  data2019-12-29 04:49:02
2019-12-29 05:19:06,916:WARNING:insert opc  data2019-12-29 05:19:06
2019-12-29 05:49:11,679:WARNING:insert opc  data2019-12-29 05:49:11
2019-12-29 06:19:16,784:WARNING:insert opc  data2019-12-29 06:19:16
2019-12-29 06:49:21,934:WARNING:insert opc  data2019-12-29 06:49:21
2019-12-29 07:19:26,940:WARNING:insert opc  data2019-12-29 07:19:26
2019-12-29 07:49:31,778:WARNING:insert opc  data2019-12-29 07:49:31
2019-12-29 08:19:36,836:WARNING:insert opc  data2019-12-29 08:19:36
2019-12-29 08:49:41,675:WARNING:insert opc  data2019-12-29 08:49:41
2019-12-29 09:19:46,639:WARNING:insert opc  data2019-12-29 09:19:46
2019-12-29 09:49:51,487:WARNING:insert opc  data2019-12-29 09:49:51
2019-12-29 10:19:56,665:WARNING:insert opc  data2019-12-29 10:19:56
2019-12-29 10:50:01,540:WARNING:insert opc  data2019-12-29 10:50:01
2019-12-29 11:20:06,071:WARNING:insert opc  data2019-12-29 11:20:06
2019-12-29 11:50:11,080:WARNING:insert opc  data2019-12-29 11:50:11
2019-12-29 12:20:15,964:WARNING:insert opc  data2019-12-29 12:20:15
2019-12-29 12:50:21,005:WARNING:insert opc  data2019-12-29 12:50:21
2019-12-29 13:20:25,747:WARNING:insert opc  data2019-12-29 13:20:25
2019-12-29 13:50:30,689:WARNING:insert opc  data2019-12-29 13:50:30
2019-12-29 14:20:35,961:WARNING:insert opc  data2019-12-29 14:20:35
2019-12-29 14:50:41,741:WARNING:insert opc  data2019-12-29 14:50:41
2019-12-29 15:20:45,748:WARNING:insert opc  data2019-12-29 15:20:45
2019-12-29 15:50:50,427:WARNING:insert opc  data2019-12-29 15:50:50
2019-12-29 16:20:55,480:WARNING:insert opc  data2019-12-29 16:20:55
2019-12-29 16:51:00,467:WARNING:insert opc  data2019-12-29 16:51:00
2019-12-29 17:21:05,387:WARNING:insert opc  data2019-12-29 17:21:05
2019-12-29 17:51:10,441:WARNING:insert opc  data2019-12-29 17:51:10
2019-12-29 18:21:15,401:WARNING:insert opc  data2019-12-29 18:21:15
2019-12-29 18:51:20,269:WARNING:insert opc  data2019-12-29 18:51:20
2019-12-29 19:21:25,209:WARNING:insert opc  data2019-12-29 19:21:25
2019-12-29 19:51:29,847:WARNING:insert opc  data2019-12-29 19:51:29
2019-12-29 20:21:35,040:WARNING:insert opc  data2019-12-29 20:21:35
2019-12-29 20:51:39,893:WARNING:insert opc  data2019-12-29 20:51:39
2019-12-29 21:21:44,701:WARNING:insert opc  data2019-12-29 21:21:44
2019-12-29 21:51:49,627:WARNING:insert opc  data2019-12-29 21:51:49
2019-12-29 22:21:54,612:WARNING:insert opc  data2019-12-29 22:21:54
2019-12-29 22:51:59,583:WARNING:insert opc  data2019-12-29 22:51:59
2019-12-29 23:22:04,479:WARNING:insert opc  data2019-12-29 23:22:04
2019-12-29 23:52:09,196:WARNING:insert opc  data2019-12-29 23:52:09
2019-12-30 00:22:13,927:WARNING:insert opc  data2019-12-30 00:22:13
2019-12-30 00:52:18,656:WARNING:insert opc  data2019-12-30 00:52:18
2019-12-30 01:22:23,647:WARNING:insert opc  data2019-12-30 01:22:23
2019-12-30 01:52:28,384:WARNING:insert opc  data2019-12-30 01:52:28
2019-12-30 02:22:33,060:WARNING:insert opc  data2019-12-30 02:22:33
2019-12-30 02:52:37,900:WARNING:insert opc  data2019-12-30 02:52:37
2019-12-30 03:22:42,924:WARNING:insert opc  data2019-12-30 03:22:42
2019-12-30 03:52:48,182:WARNING:insert opc  data2019-12-30 03:52:48
2019-12-30 04:22:53,207:WARNING:insert opc  data2019-12-30 04:22:53
2019-12-30 04:52:58,073:WARNING:insert opc  data2019-12-30 04:52:58
2019-12-30 05:23:02,876:WARNING:insert opc  data2019-12-30 05:23:02
2019-12-30 05:53:07,803:WARNING:insert opc  data2019-12-30 05:53:07
2019-12-30 06:23:12,700:WARNING:insert opc  data2019-12-30 06:23:12
2019-12-30 06:53:17,744:WARNING:insert opc  data2019-12-30 06:53:17
2019-12-30 07:23:22,807:WARNING:insert opc  data2019-12-30 07:23:22
2019-12-30 07:53:27,599:WARNING:insert opc  data2019-12-30 07:53:27
2019-12-30 08:23:32,666:WARNING:insert opc  data2019-12-30 08:23:32
2019-12-30 08:53:37,685:WARNING:insert opc  data2019-12-30 08:53:37
2019-12-30 09:23:42,606:WARNING:insert opc  data2019-12-30 09:23:42
2019-12-30 09:53:47,845:WARNING:insert opc  data2019-12-30 09:53:47
2019-12-30 10:23:52,919:WARNING:insert opc  data2019-12-30 10:23:52
2019-12-30 10:53:58,151:WARNING:insert opc  data2019-12-30 10:53:58
2019-12-30 11:24:03,306:WARNING:insert opc  data2019-12-30 11:24:03
2019-12-30 11:54:08,146:WARNING:insert opc  data2019-12-30 11:54:08
2019-12-30 12:24:13,157:WARNING:insert opc  data2019-12-30 12:24:13
2019-12-30 12:54:18,112:WARNING:insert opc  data2019-12-30 12:54:18
2019-12-30 13:24:23,217:WARNING:insert opc  data2019-12-30 13:24:23
2019-12-30 13:54:28,455:WARNING:insert opc  data2019-12-30 13:54:28
2019-12-30 14:24:33,212:WARNING:insert opc  data2019-12-30 14:24:33
2019-12-30 14:54:38,538:WARNING:insert opc  data2019-12-30 14:54:38
2019-12-30 15:24:43,603:WARNING:insert opc  data2019-12-30 15:24:43
2019-12-30 15:54:48,908:WARNING:insert opc  data2019-12-30 15:54:48
2020-01-02 16:30:23,973:WARNING:/mnt/share/新建 Microsoft Excel 工作表.xlsxhas been read at/mnt/share/新建 Microsoft Excel 工作表.xlsx~RF4e7cfa6d.TMP ---->>>>2020-01-02 16:30:23 

2020-01-03 11:02:14,108:WARNING:start thread:mq-thread
2020-01-03 11:02:14,110:WARNING:start thread:pc_lpc
2020-01-03 11:03:17,429:WARNING:start thread:mq-thread
2020-01-03 11:03:17,446:WARNING:start thread:pc_lpc
2020-01-03 11:03:17,472:WARNING:custmer wait for mes---->>opc
2020-01-03 11:03:20,471:ERROR:Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38410)>; error=113 (No route to host)
2020-01-03 11:03:20,471:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:03:20,472:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:03:20,473:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:03:20,474:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:03:20,474:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:03:20,474:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:03:28,495:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38414)>; error=113 (No route to host)
2020-01-03 11:03:28,496:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:03:28,496:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:03:28,496:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:03:28,496:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:03:28,496:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:03:28,496:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:03:36,519:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38418)>; error=113 (No route to host)
2020-01-03 11:03:36,520:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:03:36,520:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:03:36,520:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:03:36,520:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:03:36,520:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:03:36,521:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:06:38,885:WARNING:start thread:mq-thread
2020-01-03 11:06:38,888:WARNING:start thread:pc_lpc
2020-01-03 11:06:38,944:WARNING:custmer wait for mes---->>opc
2020-01-03 11:06:41,927:ERROR:Socket failed to connect: <socket.socket fd=15, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38432)>; error=113 (No route to host)
2020-01-03 11:06:41,927:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:06:41,928:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:06:41,929:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:06:41,930:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:06:41,930:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:06:41,930:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:06:49,951:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38438)>; error=113 (No route to host)
2020-01-03 11:06:49,951:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:06:49,952:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:06:49,952:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:06:49,952:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:06:49,952:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:06:49,952:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:06:57,973:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38442)>; error=113 (No route to host)
2020-01-03 11:06:57,973:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:06:57,974:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:06:57,974:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:06:57,974:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:06:57,974:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:06:57,974:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:10:37,194:WARNING:start thread:mq-thread
2020-01-03 11:10:37,195:WARNING:start thread:pc_lpc
2020-01-03 11:10:37,265:WARNING:custmer wait for mes---->>opc
2020-01-03 11:10:40,239:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38458)>; error=113 (No route to host)
2020-01-03 11:10:40,239:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:10:40,240:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:10:40,241:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:10:40,242:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:10:40,242:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:10:40,242:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:10:48,263:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38478)>; error=113 (No route to host)
2020-01-03 11:10:48,263:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:10:48,264:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:10:48,264:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:10:48,264:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:10:48,264:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:10:48,264:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:10:56,285:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38484)>; error=113 (No route to host)
2020-01-03 11:10:56,285:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:10:56,286:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:10:56,286:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:10:56,286:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:10:56,286:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:10:56,286:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:11:04,307:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38488)>; error=113 (No route to host)
2020-01-03 11:11:04,308:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:11:04,308:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:11:04,308:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:11:04,308:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:11:04,308:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:11:04,309:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:36:23,776:WARNING:start thread:mq-thread
2020-01-03 11:36:23,782:WARNING:start thread:pc_lpc
2020-01-03 11:36:23,828:WARNING:custmer wait for mes---->>opc
2020-01-03 11:36:26,819:ERROR:Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38548)>; error=113 (No route to host)
2020-01-03 11:36:26,819:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:36:26,820:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:36:26,821:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:36:26,821:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:36:26,822:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:36:26,822:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:36:34,843:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38552)>; error=113 (No route to host)
2020-01-03 11:36:34,844:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:36:34,844:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:36:34,844:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:36:34,844:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:36:34,844:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:36:34,844:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:36:42,865:ERROR:Socket failed to connect: <socket.socket fd=14, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 38556)>; error=113 (No route to host)
2020-01-03 11:36:42,866:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:36:42,866:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:36:42,866:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:36:42,866:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:36:42,866:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:36:42,867:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 11:46:36,112:WARNING:start thread:mq-thread
2020-01-03 11:46:36,114:WARNING:start thread:pc_lpc
2020-01-03 11:46:36,159:WARNING:custmer wait for mes---->>opc
2020-01-03 11:46:39,151:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39064)>; error=113 (No route to host)
2020-01-03 11:46:39,151:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 11:46:39,152:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 11:46:39,153:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 11:46:39,154:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:46:39,154:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 11:46:39,154:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 12:56:08,290:WARNING:start thread:mq-thread
2020-01-03 12:56:08,293:WARNING:start thread:pc_lpc
2020-01-03 12:56:08,354:WARNING:custmer wait for mes---->>opc
2020-01-03 12:56:52,152:WARNING:start thread:mq-thread
2020-01-03 12:56:52,172:WARNING:start thread:pc_lpc
2020-01-03 12:56:52,247:WARNING:custmer wait for mes---->>opc
2020-01-03 13:00:56,597:WARNING:start thread:mq-thread
2020-01-03 13:00:56,601:WARNING:start thread:pc_lpc
2020-01-03 13:00:56,656:WARNING:custmer wait for mes---->>opc
2020-01-03 13:01:55,879:WARNING:start thread:mq-thread
2020-01-03 13:01:55,883:WARNING:start thread:pc_lpc
2020-01-03 13:01:55,933:WARNING:custmer wait for mes---->>opc
2020-01-03 13:01:58,915:ERROR:Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39714)>; error=113 (No route to host)
2020-01-03 13:01:58,915:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 13:01:58,916:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 13:01:58,917:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 13:01:58,918:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 13:01:58,918:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 13:01:58,918:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 13:02:06,941:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39722)>; error=113 (No route to host)
2020-01-03 13:02:06,942:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 13:02:06,942:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 13:02:06,942:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 13:02:06,942:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 13:02:06,942:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 13:02:06,943:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 13:02:14,963:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39726)>; error=113 (No route to host)
2020-01-03 13:02:14,964:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 13:02:14,964:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 13:02:14,964:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 13:02:14,964:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 13:02:14,964:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 13:02:14,965:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:13:21,019:WARNING:start thread:mq-thread
2020-01-03 14:13:21,027:WARNING:start thread:pc_lpc
2020-01-03 14:13:21,069:WARNING:custmer wait for mes---->>opc
2020-01-03 14:13:24,055:ERROR:Socket failed to connect: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39840)>; error=113 (No route to host)
2020-01-03 14:13:24,055:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:13:24,056:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:13:24,057:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:13:24,058:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:24,058:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:24,058:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:13:32,081:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39848)>; error=113 (No route to host)
2020-01-03 14:13:32,081:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:13:32,082:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:13:32,082:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:13:32,082:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:32,082:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:32,082:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:13:40,103:ERROR:Socket failed to connect: <socket.socket fd=8, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39852)>; error=113 (No route to host)
2020-01-03 14:13:40,104:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:13:40,104:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:13:40,104:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:13:40,104:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:40,104:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:40,105:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:13:48,123:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39856)>; error=113 (No route to host)
2020-01-03 14:13:48,124:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:13:48,124:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:13:48,124:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:13:48,124:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:48,124:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:48,125:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:13:56,145:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39866)>; error=113 (No route to host)
2020-01-03 14:13:56,146:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:13:56,146:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:13:56,146:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:13:56,146:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:56,146:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:13:56,147:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:14:04,165:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39870)>; error=113 (No route to host)
2020-01-03 14:14:04,166:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:14:04,166:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:14:04,166:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:14:04,166:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:04,166:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:04,166:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:14:12,187:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39874)>; error=113 (No route to host)
2020-01-03 14:14:12,188:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:14:12,188:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:14:12,188:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:14:12,188:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:12,188:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:12,189:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:14:20,209:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39880)>; error=113 (No route to host)
2020-01-03 14:14:20,210:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:14:20,210:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:14:20,210:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:14:20,210:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:20,210:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:20,210:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:14:28,231:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39890)>; error=113 (No route to host)
2020-01-03 14:14:28,232:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:14:28,232:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:14:28,232:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:14:28,232:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:28,232:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:28,233:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:14:29,354:WARNING:/mnt/share/123456.xlsxhas been read at/mnt/share/123456.xlsx ---->>>>2020-01-03 10:54:43 

2020-01-03 14:14:36,255:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39894)>; error=113 (No route to host)
2020-01-03 14:14:36,256:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:14:36,256:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:14:36,256:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:14:36,256:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:36,256:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:36,257:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:14:44,277:ERROR:Socket failed to connect: <socket.socket fd=11, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.172', 39898)>; error=113 (No route to host)
2020-01-03 14:14:44,278:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.239', 5672))
2020-01-03 14:14:44,278:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-01-03 14:14:44,278:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-01-03 14:14:44,278:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:44,278:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-01-03 14:14:44,279:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-01-03 14:15:26,224:WARNING:/mnt/share/123456.xlsxhas been read at/mnt/share/123456.xlsx ---->>>>2020-01-03 10:54:43 

2020-01-03 15:06:38,204:WARNING:/mnt/share/1 - 副本.xlsxhas been read at/mnt/share/1 - 副本.xlsx ---->>>>2020-01-03 14:59:58 

2020-01-08 15:09:43,635:WARNING:/mnt/share/来料翻新.xlsxhas been read at/mnt/share/来料翻新.xlsx ---->>>>2020-01-08 15:05:07 

2020-01-08 15:11:57,976:WARNING:Failed processing format-parameters; Python 'timestamp' cannot be converted to a MySQL type
2020-01-08 15:20:52,725:WARNING:1366 (HY000): Incorrect string value: '\xE6\x9D\xA5\xE6\x96\x99...' for column 'filepath' at row 1
2020-01-08 15:35:22,971:WARNING:start thread:mq-thread
2020-01-08 15:35:22,975:WARNING:start thread:pc_lpc
2020-01-08 15:35:23,027:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 15:35:23,032:WARNING:custmer wait for mes---->>opc
2020-01-08 15:39:01,524:WARNING:start thread:mq-thread
2020-01-08 15:39:01,529:WARNING:start thread:pc_lpc
2020-01-08 15:39:01,573:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 15:39:01,580:WARNING:custmer wait for mes---->>opc
2020-01-08 16:08:58,374:WARNING:start thread:mq-thread
2020-01-08 16:08:58,397:WARNING:start thread:pc_lpc
2020-01-08 16:08:58,509:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:08:58,530:WARNING:custmer wait for mes---->>opc
2020-01-08 16:13:58,229:WARNING:start thread:mq-thread
2020-01-08 16:13:58,240:WARNING:start thread:pc_lpc
2020-01-08 16:13:58,328:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:13:58,338:WARNING:custmer wait for mes---->>opc
2020-01-08 16:27:06,043:WARNING:insert opc  data2020-01-08 16:27:06
2020-01-08 16:28:40,522:WARNING:start thread:mq-thread
2020-01-08 16:28:40,533:WARNING:start thread:pc_lpc
2020-01-08 16:28:40,633:WARNING:custmer wait for mes---->>opc
2020-01-08 16:28:40,654:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:28:47,302:WARNING:start thread:mq-thread
2020-01-08 16:28:47,307:WARNING:start thread:pc_lpc
2020-01-08 16:28:47,402:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:28:47,420:WARNING:custmer wait for mes---->>opc
2020-01-08 16:28:57,387:WARNING:start thread:mq-thread
2020-01-08 16:28:57,396:WARNING:start thread:pc_lpc
2020-01-08 16:28:57,491:WARNING:custmer wait for mes---->>opc
2020-01-08 16:28:57,510:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:33:45,288:WARNING:start thread:mq-thread
2020-01-08 16:33:45,296:WARNING:start thread:pc_lpc
2020-01-08 16:33:45,426:WARNING:custmer wait for mes---->>opc
2020-01-08 16:33:45,429:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:34:09,384:WARNING:start thread:mq-thread
2020-01-08 16:34:09,390:WARNING:start thread:pc_lpc
2020-01-08 16:34:09,512:WARNING:custmer wait for mes---->>opc
2020-01-08 16:34:09,520:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:35:55,878:WARNING:start thread:mq-thread
2020-01-08 16:35:55,911:WARNING:start thread:pc_lpc
2020-01-08 16:35:56,001:WARNING:custmer wait for mes---->>>rabbitmq_LPC
2020-01-08 16:35:56,031:WARNING:custmer wait for mes---->>opc
2020-03-19 11:13:36,155:WARNING:Unread result found
2020-03-19 11:13:53,256:WARNING:Unread result found
2020-03-19 11:14:09,516:WARNING:Unread result found
2020-03-19 11:16:22,681:WARNING:Unread result found
2020-03-19 11:16:22,681:WARNING:Unread result found
2020-03-19 15:29:53,010:WARNING:Unread result found
2020-03-19 15:29:53,010:WARNING:Unread result found
2020-03-19 15:34:54,933:WARNING:Unread result found
2020-03-19 15:39:57,803:WARNING:Unread result found
2020-03-19 15:45:01,644:WARNING:Unread result found
2020-03-19 15:46:09,426:WARNING:Unread result found
2020-03-19 15:46:09,426:WARNING:Unread result found
2020-03-19 15:50:53,315:WARNING:Unread result found
2020-03-19 15:51:59,664:WARNING:Unread result found
2020-03-19 15:52:28,283:WARNING:Unread result found
2020-03-19 15:52:41,784:WARNING:1
2020-03-19 15:52:59,490:WARNING:Unread result found
2020-03-19 15:53:14,583:WARNING:2
2020-03-19 15:56:42,161:WARNING:Unread result found
2020-03-19 15:56:42,161:WARNING:Unread result found
2020-03-19 15:56:42,162:WARNING:Unread result found
2020-03-19 15:56:42,163:WARNING:Unread result found
2020-03-19 15:56:48,364:WARNING:1
2020-03-19 15:56:48,713:WARNING:Unread result found
2020-03-19 15:56:55,398:WARNING:2
2020-03-19 15:56:55,750:WARNING:Unread result found
2020-04-10 17:03:36,488:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,513:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,514:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,518:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,519:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,520:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,520:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,521:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,522:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,522:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,523:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,524:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,525:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,526:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,526:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,527:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,528:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,528:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,529:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,530:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,530:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,531:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,531:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,531:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,532:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,532:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,532:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,533:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,533:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,534:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,534:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,534:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,535:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,535:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,535:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,536:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,536:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,537:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,537:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-10 17:03:36,537:WARNING:1054 (42S22): Unknown column 'nan' in 'field list'
2020-04-16 09:51:55,794:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,826:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,827:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,828:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,829:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,830:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,831:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,832:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,833:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,833:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,834:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,835:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,836:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,837:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 09:51:55,838:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,625:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,626:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,627:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,627:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,627:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,628:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,628:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,628:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,629:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,629:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,630:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,630:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,630:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,631:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:25:30,631:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,add1,add2,add3,add4,data0,data1,data2,data3,data4,data5,data6,da' at line 1
2020-04-16 10:28:48,444:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(2,'13:20:00','2020-04-08 00:00:00',CURRENT_' at line 1
2020-04-16 10:28:48,444:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(1,0,'2019-12-25 00:00:00',CURRENT_TIMESTAMP' at line 1
2020-04-16 10:28:48,445:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(2,'07:20:00',0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,445:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(3,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,446:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(4,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,446:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(4,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,446:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(4,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,447:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(5,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,447:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(5,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,448:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(5,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,449:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(6,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,450:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(6,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,451:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(6,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:28:48,452:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(7,'/','2019-12-17 00:00:00',CURRENT_TIMESTA' at line 1
2020-04-16 10:28:48,452:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm) VALUES(8,0,0,CURRENT_TIMESTAMP())' at line 1
2020-04-16 10:41:01,387:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,388:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,389:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,390:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,391:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,391:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,392:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,393:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,393:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,394:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,395:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,395:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,396:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,396:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:41:01,397:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES('paralist[\"index\"]','paralist[\"time\"]'' at line 1
2020-04-16 10:51:11,222:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,223:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,224:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,225:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,225:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,226:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,227:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,228:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,229:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,229:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,230:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,231:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,232:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,232:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:51:11,233:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'paralist[\"time\"]','paralist[\"date\"]' at line 1
2020-04-16 10:52:30,374:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,375:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,376:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,377:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,378:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,378:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,379:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,380:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,380:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,381:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,382:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,382:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,383:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,384:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 10:52:30,384:WARNING:1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'index,time,date,create_dt_tm)  VALUES(2,'7:50:00','2020/1/12',CURRENT_TIMESTAMP(' at line 1
2020-04-16 11:01:14,671:WARNING:1292 (22007): Incorrect time value: '13点22分' for column 'time' at row 1
2020-04-16 11:01:14,686:WARNING:1292 (22007): Incorrect time value: '/' for column 'time' at row 1
2020-04-16 11:01:24,265:WARNING:1292 (22007): Incorrect time value: '/' for column 'time' at row 1
2020-04-29 11:03:12,509:WARNING:start thread:st_arc
2020-04-29 11:03:12,574:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-29 11:13:51,563:WARNING:start thread:st_arc2
2020-04-29 11:13:51,613:WARNING:custmer wait for mes---->>>rabbitmq_ARC2
2020-04-29 11:14:03,033:WARNING:start thread:st_arc2
2020-04-29 11:14:03,240:WARNING:custmer wait for mes---->>>rabbitmq_ARC2
2020-04-29 11:15:42,097:WARNING:start thread:st_arc2
2020-04-29 11:15:42,151:WARNING:custmer wait for mes---->>>rabbitmq_ARC2
2020-04-30 13:09:13,756:WARNING:start thread:st_arc1
2020-04-30 13:09:13,793:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:12:31,776:WARNING:start thread:st_arc1
2020-04-30 13:12:31,817:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:13:56,531:WARNING:start thread:st_arc1
2020-04-30 13:13:56,566:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:14:40,710:WARNING:start thread:st_arc1
2020-04-30 13:14:40,751:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:14:56,930:WARNING:start thread:st_arc1
2020-04-30 13:14:56,978:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:18:45,734:WARNING:start thread:st_arc1
2020-04-30 13:18:45,777:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:23:56,407:WARNING:start thread:st_arc1
2020-04-30 13:23:56,442:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:23:56,443:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,444:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,444:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,445:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,446:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,446:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,447:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,447:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,448:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,448:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,449:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,449:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,450:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,450:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,450:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,451:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,451:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,451:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,452:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,452:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,453:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,453:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,454:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,454:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,454:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:23:56,881:WARNING:1146 (42S02): Table 'inss_mes.TB_ST_ARC' doesn't exist
2020-04-30 13:26:39,178:WARNING:start thread:st_arc1
2020-04-30 13:26:39,215:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-04-30 13:37:39,862:WARNING:start thread:st_arc1
2020-04-30 13:37:39,903:WARNING:custmer wait for mes---->>>rabbitmq_ARC1
2020-05-07 15:08:34,737:WARNING:start thread:st_arc1
2020-05-07 15:08:37,753:ERROR:Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.166', 48878)>; error=113 (No route to host)
2020-05-07 15:08:37,753:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.237', 5672))
2020-05-07 15:08:37,753:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-05-07 15:08:37,755:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-05-07 15:08:37,756:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:08:37,756:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:08:37,756:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-05-07 15:08:56,468:WARNING:start thread:st_arc1
2020-05-07 15:08:59,485:ERROR:Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.166', 48884)>; error=113 (No route to host)
2020-05-07 15:08:59,485:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.237', 5672))
2020-05-07 15:08:59,486:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-05-07 15:08:59,487:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-05-07 15:08:59,488:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:08:59,488:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:08:59,488:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-05-07 15:09:53,081:WARNING:start thread:st_arc1
2020-05-07 15:09:56,099:ERROR:Socket failed to connect: <socket.socket fd=9, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.166', 48890)>; error=113 (No route to host)
2020-05-07 15:09:56,099:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.237', 5672))
2020-05-07 15:09:56,099:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-05-07 15:09:56,101:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-05-07 15:09:56,102:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:09:56,102:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:09:56,102:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-05-07 15:15:19,240:WARNING:start thread:st_arc1
2020-05-07 15:15:19,240:WARNING:start thread:st_arc2
2020-05-07 15:15:22,265:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.166', 48898)>; error=113 (No route to host)
2020-05-07 15:15:22,265:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.237', 5672))
2020-05-07 15:15:22,265:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-05-07 15:15:22,267:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-05-07 15:15:22,268:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:15:22,268:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:15:22,268:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-05-07 15:22:08,264:WARNING:start thread:st_arc1
2020-05-07 15:22:08,265:WARNING:start thread:st_arc2
2020-05-07 15:22:11,291:ERROR:Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.11.166', 48908)>; error=113 (No route to host)
2020-05-07 15:22:11,291:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.11.237', 5672))
2020-05-07 15:22:11,292:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-05-07 15:22:11,293:ERROR:Socket failed to connect: <socket.socket fd=13, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('10.10.10.248', 42650)>; error=113 (No route to host)
2020-05-07 15:22:11,294:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-05-07 15:22:11,295:ERROR:TCP Connection attempt failed: OSError(113, 'No route to host'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.10.10.54', 5672))
2020-05-07 15:22:11,295:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:22:11,295:ERROR:AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: OSError(113, 'No route to host')
2020-05-07 15:22:11,296:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:22:11,296:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2020-05-07 15:22:11,296:ERROR:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None.
2020-05-07 15:22:11,298:ERROR:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:22:11,299:ERROR:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: OSError(113, 'No route to host'); first exception - None
2020-05-07 15:22:11,299:ERROR:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/python3Dir/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
